export const STEP_PRESET_INFO_SYMBOL = Symbol('STEP PRESET INFO');
export const STEP_CLOSURE_DETAILS_SYMBOL = Symbol('STEP CLOSURE DETAILS');
export const STEP_SUMMARY_SYMBOL = Symbol('STEP SUMMARY');
